app = 'video-streaming-platform-backend'
primary_region = 'fra'

[build]
  dockerfile = './Dockerfile'
  build-target = 'runner'

[deploy]
  strategy = 'rolling'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 150
    soft_limit = 100

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
